version: '3.8'

services:
  angular-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Changed to use port 4200 to match Spotify config
    container_name: music-app-frontend
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3001:3000"  # Changed to use port 3001
    container_name: music-app-backend  # Added explicit container name
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/mydatabase
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: music-app-db  # Added explicit container name
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydatabase
    ports:
      - "5433:5432"  # Changed to use port 5433
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
